server:
  port: 8881
spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        serviceId: config-server
  rabbitmq:
    host: localhost
    port: 5672

#      uri: http://localhost:8888/
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false

